import type { IProductBenefits } from "./IProductBenefits";
import type { ICapsuleInfoModel } from "./api/ICapsuleInfoModel";
import type { IHealthCategories } from "./api/IHealthCategories";
import type IPriceInfoModel from "./api/IPriceInfoModel";
import type { IProducerModel } from "./api/IProducerModel";
import type { ISupplementTeamProducts } from "./api/ISupplementTeamProducts";

export default interface ISingleProductModel {
	id: string;
	name?: string;
	imageUrl: string;
	imageKey: string;
	description?: string;
	price: number;
	teamName?: string;
	wholesalePrice: number;
	retailPrice?: string;
	vat?: string;
	rabbleMarkUp?: string;
	rrp: number;
	status?: string;
	orderUnit?: string;
	subUnit?: string;
	quantityOfSubUnitPerOrder?: number;
	unitsOfMeasurePerSubUnit?: string;
	measuresPerSubUnit?: number;
	approvalStatus?: string;
	stock?: number;
	tags?: string[];
	priceInfo?: IPriceInfoModel[];
	pricePerCount?: number;
	capsuleInfo?: ICapsuleInfoModel[];
	formulationSummary?: string[];
	productBenefits?: IProductBenefits[];
	createdAt?: string;
	updatedAt?: string;
	type?: string;
	producer?: IProducerModel;
	partionedProducts?: [];
	members: number;
	isComming: boolean;
	gallery: string[];
	orderId?: string;
	supplementTeamProducts?: ISupplementTeamProducts;
	healthCategories?: IHealthCategories[];
	nextPriceDiscountLevel?: {
		membersNeeded: number;
		expectedDiscount: number;
	};
	deliveryDate?: string;
	daysUntilNextDrop?: number;
	alignmentPoucheSize?: number;
	poucheSize?: number;
	rrpPerCount?: number;
	discount?: number;
	activePercentageDiscount?: number;
	gramsPerCount?: number;
	pricePerPoche?: number;
	leadTime?: number;
	firstDelivery?: boolean;
}
